# Generated by Django 4.2.4 on 2023-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='public_id',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
